/*globals define, WebGMEGlobal*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Sun Dec 11 2022 15:40:05 GMT+0000 (Coordinated Universal Time).
 */

define([/*jointjs,*/'css!./styles/SimPetriNetWidget.css'], function (/*joint*/) {
    'use strict';

    var WIDGET_CLASS = 'sim-petri-net';

    function SimPetriNetWidget(logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this.nodes = {};
        this._initialize();

        this._logger.debug('ctor finished');
    }

    SimPetriNetWidget.prototype._initialize = function () {
        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        // set widget class
        this._el.addClass(WIDGET_CLASS);

        // Create a dummy header
        this._el.append('<h3>SimPetriNet Events:</h3>');

        // Registering to events can be done with jQuery (as normal)
        this._el.on('dblclick', function (event) {
            event.stopPropagation();
            event.preventDefault();
            self.onBackgroundDblClick();
        });
    };

    SimPetriNetWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    // Adding/Removing/Updating items
    SimPetriNetWidget.prototype.addNode = function (desc) {
        if (desc) {
            // Add node to a table of nodes
            var node = document.createElement('div'),
                label = 'children';

            if (desc.childrenIds.length === 1) {
                label = 'child';
            }

            this.nodes[desc.id] = desc;
            node.innerHTML = 'Adding node "' + desc.name + '" (click to view). It has ' +
                desc.childrenIds.length + ' ' + label + '.';

            this._el.append(node);
            node.onclick = this.onNodeClick.bind(this, desc.id);
        }
    };

    SimPetriNetWidget.prototype.removeNode = function (gmeId) {
        var desc = this.nodes[gmeId];
        this._el.append('<div>Removing node "' + desc.name + '"</div>');
        delete this.nodes[gmeId];
    };

    SimPetriNetWidget.prototype.updateNode = function (desc) {
        if (desc) {
            this._logger.debug('Updating node:', desc);
            this._el.append('<div>Updating node "' + desc.name + '"</div>');
        }
    };

    SimPetriNetWidget.prototype.fireEvent = function (element) {
    /*element.paths_from.forEach(p => {
        if (p.tokens > 0)
            this._webgmePetriNet.places[p.id].tokens -= 1
    })

    element.paths_from.forEach(p => {
        this._webgmePetriNet.places[p.id].tokens += 1
    })*/
  }

  SimPetriNetWidget.prototype.resetPetriNet = function () {
      return
  };

  SimPetriNetWidget.prototype.initPetriNet = function (petriNet) {
      return
  };

  SimPetriNetWidget.prototype.destroyPetriNet = function (petriNet) {
      return
  };

    /* * * * * * * * Visualizer event handlers * * * * * * * */

    SimPetriNetWidget.prototype.onNodeClick = function (/*id*/) {
        // This currently changes the active node to the given id and
        // this is overridden in the controller.
    };

    SimPetriNetWidget.prototype.onBackgroundDblClick = function () {
        this._el.append('<div>Background was double-clicked!!</div>');
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    SimPetriNetWidget.prototype.destroy = function () {
    };

    SimPetriNetWidget.prototype.onActivate = function () {
        this._logger.debug('SimPetriNetWidget has been activated');
    };

    SimPetriNetWidget.prototype.onDeactivate = function () {
        this._logger.debug('SimPetriNetWidget has been deactivated');
    };

    return SimPetriNetWidget;
});
